# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23e9538a0b98bc29ad20d28874e33e49ed6e4954608701d90ff083deb15344b960a8cb4e4c07733720b240deabc7725141421bb31c9bf5474ab82d2f6a250059

test:
  secret_key_base: a8bd97585d9dbea90dc66790b9bd39594cdca5b66e5f58a36fdd138318985f194a1a73dcf61832c6e0ca920666a36b3710b7d7e8c45191f04bfc4d3c1695fab8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
